### default args ###

# keep run mapping bam file and reference index files.
# cache these files, so you do not need to re-run some analysis when you add more sequening reads
keep_internal: false
# keep dicarded reads (untrimmed, too-short, unmapped...), for debugs purpose.
# Most of the time, you do not need these files. Set it as `false` to save storage.
keep_discarded: false
# Whether remove atypical adapter
trim_p5: false

### build in args ###
# if you change build in args, add the whole block rather than some records!!

cutoff:
  ## processing reads
  # STAR `outFilterMatchNminOverLread`
  min_match_prop: 0.8
  ## calling sites
  # prefilter sites show >= x gaps in total among all samples in each group
  min_group_gap: 5
  # prefilter sites show >= x sequencing coverage in total among all samples in each group
  min_group_depth: 10
  # prefilter sites show >= x deletion ratio among all samples in each group
  min_group_ratio: 0.02
  # only analysis putative sites that show pass prefilter in >= x groups
  min_group_num: 1

adapter:
  # 20nt
  p7: AGATCGGAAGAGCACACGTC
  p5: AGTTCTACAGTCCGACGATC

path:
  fastp: /pipeline/micromamba/bin/fastp
  cutadapt: /pipeline/micromamba/bin/cutadapt
  bgzip: /pipeline/micromamba/bin/bgzip
  bowtie2: /pipeline/micromamba/bin/bowtie2
  bowtie2Build: /pipeline/micromamba/bin/bowtie2-build
  star: /pipeline/micromamba/bin/STAR
  samtools: /pipeline/micromamba/bin/samtools
  bedtools: /pipeline/micromamba/bin/bedtools
  multiqc: /pipeline/micromamba/bin/multiqc
  umicollapse: /bin/umicollapse.jar
  delfilter: /pipeline/bin/deletionFilter
  samfilter: /pipeline/bin/samFilter
  cpup: /pipeline/bin/cpup
  adjustGap: /pipeline/bin/adjustGap
  realignGap: /pipeline/bin/realignGap
