tmpdir: /tmp

cutoff:
  # prefilter sites show >= x gaps in total among all samples in each group
  min_group_gap: 5
  # prefilter sites show >= x sequencing coverage in total among all samples in each group
  min_group_depth: 10
  # prefilter sites show >= x deletion ratio among all samples in each group
  min_group_ratio: 0.02
  # only analysis putative sites that show pass prefilter in >= x groups
  min_group_num: 1

adapter:
  p7: AGATCGGAAGAGCACACGTCT

path:
  fastp: /opt/micromamba/bin/fastp
  cutadapt: /opt/micromamba/bin/cutadapt
  samtools: /opt/micromamba/bin/samtools
  bgzip: /opt/micromamba/bin/bgzip
  bowtie2: /opt/micromamba/bin/bowtie2
  bedtools: /opt/micromamba/bin/bedtools
  star: /opt/micromamba/bin/STAR
  umicollapse: /bin/umicollapse.jar
  delfilter: /opt/pipeline/bin/deletionFilter
  samfilter: /opt/pipeline/bin/samFilter
  cpup: /opt/pipeline/bin/cpup
  adjustGap: /opt/pipeline/bin/adjustGap
  realignGap: /opt/pipeline/bin/realignGap
