srcdir: /opt/pipeline/bin

path:
  bowtie2: /opt/miniconda/bin/bowtie2
  star: /opt/miniconda/bin/STAR
  samtools: /opt/miniconda/bin/samtools
  bedtools: /opt/miniconda/bin/bedtools
  rnaseqc: /opt/rnaseqc
  blast2bam: /opt/blast2bam/bin/blast2bam
  rnaseqmut: /opt/rnaseqmut/bin/rnaseqmut
  umicollapse: /opt/UMICollapse/umicollapse.jar
  featureCounts: /opt/miniconda/bin/featureCounts
  cpup: /opt/cpup/cpup

barcode:
  barcode3_r1: AGATCGGAAGAGCACACGTCTG
  barcode3_r2: AGATCGGAAGAGCGTCGTGT

# other default setting
workdir: results
threads: 24
