min_group: 1
tmp_dir: /tmp

adapter:
  p7: AGATCGGAAGAGCACACGTCT

path:
  fastp: ~/.micromamba/bin/fastp
  cutadapt: ~/.micromamba/bin/cutadapt
  samtools: ~/tools/samtools/samtools
  bgzip: ~/.local/bin/bgzip
  bowtie2: ~/.local/bin/bowtie2
  bedtools: ~/.micromamba/bin/bedtools
  star: ~/tools/STAR/bin/Linux_x86_64/STAR
  umicollapse: ~/tools/UMICollapse/umicollapse.jar
  delfilter: ../bin/deletionFilter
  samfilter: ../bin/samFilter
  cpup: ../bin/cpup
  adjustGap: ../bin/adjustGap
  realignGap: ../bin/realignGap
