min_group: 1
tmp_dir: /tmp

adapter:
  p7: AGATCGGAAGAGCACACGTCT

path:
  fastp: /opt/micromamba/bin/fastp
  cutadapt: /opt/micromamba/bin/cutadapt
  samtools: /opt/micromamba/bin/samtools
  bgzip: /opt/micromamba/bin/bgzip
  bowtie2: /opt/micromamba/bin/bowtie2
  bedtools: /opt/micromamba/bin/bedtools
  star: /opt/micromamba/bin/STAR
  umicollapse: /bin/umicollapse.jar
  delfilter: /opt/pipeline/bin/deletionFilter
  samfilter: /opt/pipeline/bin/samFilter
  cpup: /opt/pipeline/bin/cpup
  adjustGap: /opt/pipeline/bin/adjustGap
  realignGap: /opt/pipeline/bin/realignGap
