### default args ###

# keep dicarded reads (untrimmed, too-short, unmapped...), for debugs purpose.
# Most of the time, you do not need these files. Set it as `false` to save storage.
keep_discarded: true
# keep run mapping results (bam file).
# cache these files, so you do not need to re-run the analysis for previous data when you add more sequening reads
keep_internal: false

### build in args ###
# if you change build in args, add the whole block rather than some records!!

cutoff:
  ## processing reads
  # STAR `outFilterMatchNminOverLread`
  min_match_prop: 0.8
  ## calling sites
  # prefilter sites show >= x gaps in total among all samples in each group
  min_group_gap: 5
  # prefilter sites show >= x sequencing coverage in total among all samples in each group
  min_group_depth: 10
  # prefilter sites show >= x deletion ratio among all samples in each group
  min_group_ratio: 0.02
  # only analysis putative sites that show pass prefilter in >= x groups
  min_group_num: 1

adapter:
  p7: AGATCGGAAGAGCACACGTCT

path:
  fastp: /opt/micromamba/bin/fastp
  cutadapt: /opt/micromamba/bin/cutadapt
  bgzip: /opt/micromamba/bin/bgzip
  bowtie2: /opt/micromamba/bin/bowtie2
  bowtie2Build: /opt/micromamba/bin/bowtie2-build
  star: /opt/micromamba/bin/STAR
  samtools: /opt/micromamba/bin/samtools
  bedtools: /opt/micromamba/bin/bedtools
  umicollapse: /bin/umicollapse.jar
  delfilter: /opt/pipeline/bin/deletionFilter
  samfilter: /opt/pipeline/bin/samFilter
  cpup: /opt/pipeline/bin/cpup
  adjustGap: /opt/pipeline/bin/adjustGap
  realignGap: /opt/pipeline/bin/realignGap
