# Directory for all output results and analysis reports
workdir: "/scratch/gpfs/tcomi/tmp_bid/18S_SuperScript_test_redo"
       
tempdir: "/scratch/gpfs/tcomi/tmp_bid/18S_SuperScript_test_redo/tmp"

reference:
  genes:
    fa: /projects/BRANGWYNNE/projects/genomics/primary_data/2025/03_March/20250324-BrangwynneNova-LJSQ/pseudoU-BIDseq-polysome-RC-genome-18S/human_18S.fasta
  genome:
    fa: /projects/BRANGWYNNE/projects/genomics/primary_data/2025/03_March/20250324-BrangwynneNova-LJSQ/pseudoU-BIDseq-polysome-RC-genome-18S/human_18S.fasta
    star: /projects/BRANGWYNNE/projects/genomics/primary_data/2025/03_March/20250324-BrangwynneNova-LJSQ/pseudoU-BIDseq-polysome-RC-genome-18S/human_18S

config_copy: config_{date}.yaml"

cutoff:
  min_match_prop: 0
  min_group_gap: 0
  min_group_depth: 1
  min_group_ratio: 0
  min_group_num: 0

group_filter:
  combine_group_input: false
  min_passed_group: 0
  min_treated_depth: 1
  min_input_depth: 1
  min_treated_gap: 0
  min_treated_ratio: 0
  min_treated_fraction: 0
  min_fold_ratio: 0.00001
  max_p_value: 0

# only call gap sites within selected region
select_region:
  - genome

# keep run mapping bam file and reference index files.
# cache these files, so you do not need to re-run some analysis when you add more sequening reads
keep_internal: true
# keep dicarded reads (untrimmed, too-short, unmapped...), for debugging purpose.
# Most of the time, you do not need these files. Set it as `false` to save storage.
keep_discarded: true

# only keep reads that have a p7 adapter in the read1, which is important for inline barcode detection
# If inline barcode is added, this arg will be true, otherwise it will be false
trimmed_only: auto
# Whether remove atypical adapter
trim_p5: false
# Whether remove long polyA sequence
trim_polyA: false
# Whether clip match on contamination / gene reference
greedy_mapping: false
# speed up bowtie2 mapping, might lead to some FP, but can speed up significantly
speedy_mapping: false

# defualt barcode scheme
barcode: ''

# If the library is forward_stranded, true mean the R1 is in the same orientation as RNA
forward_stranded: false

sample_specification:
  base_path: /projects/BRANGWYNNE/projects/genomics/primary_data/2024/08_August/20240824-BrangwynneSPNovaPool/BIDseq/fastqs/3163__{sample}.fastq.gz
  # PlusBS-SSIIIa-read-1
  sample_regex: "{treated}{group}-read-{read}"
  treated_regex: "Plus|Minus"
  treated_name: Plus

adapter:
  # 20nt
  p7: AGATCGGAAGAGCACACGTC
  p5: AGTTCTACAGTCCGACGATC

# default to calibration curve in docker container
# calibration_curves: calibration_curves.tsv

path:
  fastp: /pipeline/micromamba/bin/fastp
  cutadapt: /pipeline/micromamba/bin/cutadapt
  bgzip: /pipeline/micromamba/bin/bgzip
  bowtie2: /pipeline/micromamba/bin/bowtie2
  bowtie2Build: /pipeline/micromamba/bin/bowtie2-build
  star: /pipeline/micromamba/bin/STAR
  samtools: /pipeline/micromamba/bin/samtools
  bedtools: /pipeline/micromamba/bin/bedtools
  multiqc: /pipeline/micromamba/bin/multiqc
  umicollapse: /bin/umicollapse.jar
  joinFastq: /pipeline/bin/joinFastq
  rcFastq: /pipeline/bin/rcFastq
  delfilter: /pipeline/bin/deletionFilter
  samfilter: /pipeline/bin/samFilter
  cpup: /pipeline/bin/cpup
  adjustGap: /pipeline/bin/adjustGap
  realignGap: /pipeline/bin/realignGap
  filterGap: /pipeline/bin/filterGap
  pickSites: /pipeline/bin/pickSites.py
