### default args ###

# keep run mapping bam file and reference index files.
# cache these files, so you do not need to re-run some analysis when you add more sequening reads
keep_internal: false
# keep dicarded reads (untrimmed, too-short, unmapped...), for debugging purpose.
# Most of the time, you do not need these files. Set it as `false` to save storage.
keep_discarded: false

# only keep reads that have a p7 adapter in the read1, which is important for inline barcode detection
# If inline barcode is added, this arg will be true, otherwise it will be false
trimmed_only: auto
# Whether remove atypical adapter
trim_p5: false
# Whether remove long polyA sequence
trim_polyA: false
# Whether clip match on contamination / gene reference
greedy_mapping: false
# speed up bowtie2 mapping, might lead to some FP, but can speed up significantly
speedy_mapping: false

# defualt barcode scheme
barcode: '-NNNNN'

# If the library is forward_stranded, true mean the R1 is in the same orientation as RNA
forward_stranded: true

### build in args ###
# if you change build in args, add the whole block rather than some records!!

cutoff:
  ## processing reads
  # STAR `outFilterMatchNminOverLread`
  min_match_prop: 0.8
  ## calling sites
  # prefilter sites show >= x gaps in total among all samples in each group
  min_group_gap: 5
  # prefilter sites show >= x sequencing coverage in total among all samples in each group
  min_group_depth: 10
  # prefilter sites show >= x deletion ratio among all samples in each group
  min_group_ratio: 0.01
  # only analysis putative sites that show pass prefilter in >= x groups
  min_group_num: 1

calibration_curves: /pipeline/calibration_curves.tsv

# only call gap sites within selected region
select_region:
  - genes
  - genome

# All the cutoff in these filter are **greater or equal to**
group_filter:
  combine_group_input: true
  min_passed_group: 1
  min_treated_depth: 20
  min_input_depth: 20
  min_treated_gap: 5
  min_treated_ratio: 0.02
  min_treated_fraction: 0.02
  min_fold_ratio: 2
  max_p_value: 0.0001

adapter:
  # 20nt
  p7: AGATCGGAAGAGCACACGTC
  p5: AGTTCTACAGTCCGACGATC

path:
  fastp: /pipeline/micromamba/bin/fastp
  cutadapt: /pipeline/micromamba/bin/cutadapt
  bgzip: /pipeline/micromamba/bin/bgzip
  bowtie2: /pipeline/micromamba/bin/bowtie2
  bowtie2Build: /pipeline/micromamba/bin/bowtie2-build
  star: /pipeline/micromamba/bin/STAR
  samtools: /pipeline/micromamba/bin/samtools
  bedtools: /pipeline/micromamba/bin/bedtools
  multiqc: /pipeline/micromamba/bin/multiqc
  umicollapse: /bin/umicollapse.jar
  joinFastq: /pipeline/bin/joinFastq
  delfilter: /pipeline/bin/deletionFilter
  samfilter: /pipeline/bin/samFilter
  cpup: /pipeline/bin/cpup
  adjustGap: /pipeline/bin/adjustGap
  realignGap: /pipeline/bin/realignGap
  filterGap: /pipeline/bin/filterGap
  pickSites: /pipeline/bin/pickSites.py
