name: bid_snake
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10.11
  - snakemake=7.18
  - click=8.1.7
  - numpy=1.26.2
  - pyfaidx=0.7.2.2
  - scipy=1.11.3
  - parasail-python=1.3.4
  - pysam=0.22.0
  - fastp=0.23.4
  - cutadapt=4.6.0
  - bowtie2=2.5.1
  - star=2.7.10b
  - samtools=1.17
  - bedtools=2.31.0
  - multiqc=1.17
  - falco  # needed?
